language: node_js
node_js:
    - "8"
    - "10"
    - "11"
install: yarn install
jobs: 
  include:
     - stage: deploy
     node_js: 10
     script: yarn prepare
cache:
  yarn: true
  directories:
    - node_modules